### ISSUE TITLE
"Fast Charge" mode not supported by kernel, revealed in AOKP UI

### ISSUE THREAD

**Issue by jeffsf** [teamacid/android_kernel_galaxys4gmtd#14]
AOKP milestone_6, SGS4G

Go to Settings > ROM Control > Statusbar, Toggles > Enabled Toggles

Select "Fast charge" and "close"

Pull down Notification bar and note the FastCharge toggle showing.

Note that the toggle can be turned on, but that the toggle does not turn blue.

Close the notification area and reopen it. Note that the toggle indicates "off"

Logcat indicates:

E/FChargeToggle(  287): Couldn't write fast_charge file
E/FChargeToggle(  287): Couldn't read fast_charge file

from com.android.systemui

Looking at frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/toggles/FChargeToggle.java confirms that it is the source of the error message.

``` java
    public static final String FAST_CHARGE_DIR = "/sys/kernel/fast_charge";
    public static final String FAST_CHARGE_FILE = "force_fast_charge";
```

Confirmed that /sys/kernel/fast_charge is not found in a running SGS4G running AOKP milestone_6

Similar code in packages/apps/ROMControl/src/com/aokp/romcontrol/service/BootService.java:

Some devices appear to have this "disabled" such as

./vendor/aokp/overlay/tf101/packages/apps/ROMControl/res/values/config.xml: <bool name="has_fast_charge">false</bool>

though I don't know how this interacts with the build system.

From what I can tell, this is a feature to allow the device to pull over the active USB device limit (typically 500 mA) by "turning off" USB connectivity. This is based on the string in packages/apps/ROMControl/res/values/strings.xml: <string name="fast_charge_warning">YOU WILL NOT BE ABLE TO CONNECT TO YOUR PC AFTER EACH REBOOT!\n\nThis setting will set fast charge ON after each reboot. While fast charge is on, you can _only_ charge your phone!</string>

**Comment by jeffsf** [comment]
Apologies for the lost XML tags above.

``` java

./packages/apps/ROMControl/res/values/config.xml:    <bool name="has_fast_charge">true</bool>
./packages/apps/ROMControl/src/com/aokp/romcontrol/AOKPPreferenceFragment.java:        hasFastCharge = getResources().getBoolean(R.bool.has_fast_charge);
```

jeff@port7:~/Documents/android-build/acidify-aokp$ fgrep -r hasFastCharge . 2>/dev/null
./packages/apps/ROMControl/src/com/aokp/romcontrol/fragments/Performance.java:        if (!hasFastCharge) {
./packages/apps/ROMControl/src/com/aokp/romcontrol/AOKPPreferenceFragment.java:    protected boolean hasFastCharge;
./packages/apps/ROMControl/src/com/aokp/romcontrol/AOKPPreferenceFragment.java:        hasFastCharge = getResources().getBoolean(R.bool.has_fast_charge);

**Comment by maxfierke** [comment]
There's a kernel driver that needs to be thrown in. It's in some of the custom i9000 and Vibrant kernels. I'll do that soon.
