### ISSUE TITLE
GP2A Light Sensor driver slow to generate events and may not generate events at all

### ISSUE THREAD

**Issue by jeffsf** [teamacid/android_kernel_galaxys4gmtd#16]
Symptom seen in auto-brightness code where the sampling time is set to 1 second, the kernel can be seen to be sampling the adc every second, but events only get seen my the SensorManager every 20 seconds at most. Sometimes the 20-second "tick" gets missed, often for long periods.

Examination of drivers/input/misc/gp2a.c shows that _gp2a_work_func_light()_ collects 20 samples in the same "bin" before generating an event. Thinking through this further, if the reported level is drifting back and forth across a bin (0-250-400-480-800-1000-1400-1550-2000-over), an event may _never_ be generated.

Note that the samples collected are _already_ trimmed and averaged in _lightsensor_get_adcvalue()_ which looks over the last 6 samples, as presently configured.

This might be related to the 4-sample Crespo hack seen (and removed) in device/samsung/galaxys4gmtd/libsensors/LightSensor.*

This issue is  related to and probably the root cause of most of the symptoms in https://github.com/teamacid/android_device_samsung_galaxys4gmtd/issues/30

**Comment by maxfierke** [comment]
Have you tried libsensors from either aries-common or epicmtd?

**Comment by jeffsf** [comment]
libsensors seems fine -- it should "do the right thing" if the kernel actually reported values "on cue" rather than every 20th one, at best.

The GP2A driver we have dates back to "Initial import of T959VUVKJ6 Kernel source drop"

Two possible ways to resolve, assuming the bin-changing issue is resolved:
- Have the kernel report values every clock, not every 20th
- Have libsensors up the sample rate requested of the kernel by a factor of 20

Thanks for the pointer to Epic as another "reference implementation" to look at!

**Comment by jeffsf** [comment]
Added GB label as the driver has been the same since at least the KJ6 drop

**Comment by jeffsf** [comment]
Should be resolved in android_kernel_galaxys4gmtd 54d8330f1432cf01cb5e2cbef0ec9de7e536a92e
