### ISSUE TITLE
Very useful repo

### ISSUE THREAD

**Issue by hampsterblade** [teamacid/android_kernel_galaxys4gmtd#3]
I just found a repo with very similar issues to all the ones we had, as well as some great fixes.  Also incorporates a proper fix for Ringtones, instead of my hacky method. I'm playing with it right now :). The repo is here:
https://github.com/dman3285/android_kernel_samsung_dempsey/

**Comment by maxfierke** [comment]
Yeah, I've been grabbing commits from another demsey kernel too. There's
some good shit in there and I probably will end up applying the ringtone
fix and reverting back to aries libaudio, or maybe crespo libaudio.
On May 15, 2012 4:43 PM, "hampsterblade" <
reply@reply.github.com>
wrote:

**Comment by hampsterblade** [comment]
Also there's a bluetooth fix in there I'm testing out now.
