### ISSUE TITLE
Reboot to download mode broken

### ISSUE THREAD

**Issue by maxfierke** [teamacid/android_kernel_galaxys4gmtd#9]
Reboot to download mode is not working. We may not be passing the correct reboot reason to S5P_INFORM6.

**Comment by bhundven** [comment]
Think you are on to something here.

For those interested, here is the call notifier chain call: https://github.com/teamacid/android_kernel_galaxys4gmtd/blob/gingerbread/arch/arm/mach-s5pv210/mach-aries.c#L204

Here are the definitions of the different REBOOT_MODEs: https://github.com/teamacid/android_kernel_galaxys4gmtd/blob/gingerbread/arch/arm/mach-s5pv210/include/mach/param.h#L75

and at the top of mach-aries (yes... our phone is herring :-P thanks for the confusion samsung) they override fastboot (which is never used): https://github.com/teamacid/android_kernel_galaxys4gmtd/blob/gingerbread/arch/arm/mach-s5pv210/mach-aries.c#L173

I've noticed from other devices that sometimes samsung enters the wrong values in these defines and certain modes don't work (like reboot or download).

We should try adding a printk that outputs "(char *)_cmd" in that call notifier (say... KERN_INFO) so we know what it thinks it is doing so we can better catch that mode as download mode.

**Comment by maxfierke** [comment]
I'm thinking I might be able to make something hacky out of this:

http://forum.xda-developers.com/showthread.php?t=1108103

Maybe.

**Comment by bhundven** [comment]
http://forum.xda-developers.com/showthread.php?t=1629359

check that out ;)
